services:
  project-master-enterprise:
    build: .
    container_name: project-master-enterprise
    restart: always
    expose:
      - "80"
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
